### ISSUE TITLE
Add windows runner to the CI

### ISSUE THREAD

**Issue by RyanJField** [FAIRDataPipeline/pyDataPipeline#21]
To ensure compatibility with windows, windows should be added as runner to the CI. To install HDF5 on windows runner see: https://github.com/FAIRDataPipeline/cppDataPipeline/blob/ryanjfield-dev/.github/workflows/fdp_cpp_api.yaml#L102

**Comment by bobturneruk** [comment]
Sure. I'll have a look. It's this branch? https://github.com/FAIRDataPipeline/pyDataPipeline/tree/feature/windows-ci

**Comment by RyanJField** [comment]
@bobturneruk I’ve got the registry to install, I’m just working on getting python to run correctly.

**Comment by RyanJField** [comment]
@bobturneruk @bruvio this is now working on the windows branch

**Comment by RyanJField** [comment]
Fixed with PR #43
