### ISSUE TITLE
Reading local token

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/pyDataPipeline#9]
I've realised that you're reading the local token in your code in the README:

```py
token = os.path.join(os.path.expanduser('~'), '.fair/registry/token')
```

The same issue arose in Java, and last week I added a fix that `${{LOCAL_TOKEN}}` in a user config gives you the token itself. I've just pushed a further fix that's probably a bit less suspect that the environment variable `FDP_LOCAL_TOKEN` also gives you the token, so you can read it in your code like you do `FDP_CONFIG_DIR`. I hope that's useful... it might be better than setting a fixed path anyway.

**Comment by RyanJField** [comment]
Thanks, I'll add this to the example. and test in CI.
